<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SamanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::unprepared("
        insert into \"saman\".\"summon_document\" ( \"ref_id\", \"is_primary\", \"created_by\", \"doc_name\", \"doc_path_thumbnail\", \"created_at\", \"doc_format\", \"updated_at\", \"doc_type\", \"doc_path\") values ( null, '0', '1', '6PW10Kbdr.pdf', null, '2021-08-11 14:44:54', 'pdf', '2021-08-11 14:44:54', 'notis_saman', 'dokumen/summon/');
insert into \"saman\".\"summon_document\" ( \"ref_id\", \"is_primary\", \"created_by\", \"doc_name\", \"doc_path_thumbnail\", \"created_at\", \"doc_format\", \"updated_at\", \"doc_type\", \"doc_path\") values ( null, '0', '1', '7RngGyM6T.pdf', null, '2021-08-11 14:51:27', 'pdf', '2021-08-11 14:51:27', 'notis_saman', 'dokumen/summon/');
insert into \"saman\".\"summon_document\" ( \"ref_id\", \"is_primary\", \"created_by\", \"doc_name\", \"doc_path_thumbnail\", \"created_at\", \"doc_format\", \"updated_at\", \"doc_type\", \"doc_path\") values ( null, '0', '1', 'a0OKRV5x4.jpg', null, '2021-08-11 15:28:00', 'jpg', '2021-08-11 15:28:00', 'notis_saman', 'dokumen/summon/');
insert into \"saman\".\"summon_document\" ( \"ref_id\", \"is_primary\", \"created_by\", \"doc_name\", \"doc_path_thumbnail\", \"created_at\", \"doc_format\", \"updated_at\", \"doc_type\", \"doc_path\") values ( null, '0', '1', '3xJAllvOC.pdf', null, '2021-08-11 15:35:45', 'pdf', '2021-08-11 15:35:45', 'notis_saman', 'dokumen/summon/');
insert into \"saman\".\"summon_document\" ( \"ref_id\", \"is_primary\", \"created_by\", \"doc_name\", \"doc_path_thumbnail\", \"created_at\", \"doc_format\", \"updated_at\", \"doc_type\", \"doc_path\") values ( null, '0', '1', 'REoWyFd1b.pdf', null, '2021-08-11 17:05:42', 'pdf', '2021-08-11 17:05:42', 'notis_saman', 'dokumen/summon/');
insert into \"saman\".\"summon_document\" ( \"ref_id\", \"is_primary\", \"created_by\", \"doc_name\", \"doc_path_thumbnail\", \"created_at\", \"doc_format\", \"updated_at\", \"doc_type\", \"doc_path\") values ( null, '0', '1', 'iEo4027LF.pdf', null, '2021-08-11 18:15:47', 'pdf', '2021-08-11 18:15:47', 'notis_saman', 'dokumen/summon/');
insert into \"saman\".\"summon_document\" ( \"ref_id\", \"is_primary\", \"created_by\", \"doc_name\", \"doc_path_thumbnail\", \"created_at\", \"doc_format\", \"updated_at\", \"doc_type\", \"doc_path\") values ( null, '0', '1', 'X6zlie5TU.pdf', null, '2021-08-11 18:17:16', 'pdf', '2021-08-11 18:17:16', 'notis_saman', 'dokumen/summon/');
insert into \"saman\".\"summon_document\" ( \"ref_id\", \"is_primary\", \"created_by\", \"doc_name\", \"doc_path_thumbnail\", \"created_at\", \"doc_format\", \"updated_at\", \"doc_type\", \"doc_path\") values ( null, '0', '1', 'f3K0fpGJn.pdf', null, '2021-08-11 18:19:09', 'pdf', '2021-08-11 18:19:09', 'notis_saman', 'dokumen/summon/');
insert into \"saman\".\"summon_document\" ( \"ref_id\", \"is_primary\", \"created_by\", \"doc_name\", \"doc_path_thumbnail\", \"created_at\", \"doc_format\", \"updated_at\", \"doc_type\", \"doc_path\") values ( null, '0', '1', 'HjgGYfkIa.pdf', null, '2021-08-11 18:21:10', 'pdf', '2021-08-11 18:21:10', 'notis_saman', 'dokumen/summon/');
insert into \"saman\".\"summon_document\" ( \"ref_id\", \"is_primary\", \"created_by\", \"doc_name\", \"doc_path_thumbnail\", \"created_at\", \"doc_format\", \"updated_at\", \"doc_type\", \"doc_path\") values ( null, '0', '1', '70O0p7uxF.pdf', null, '2021-08-11 18:22:41', 'pdf', '2021-08-11 18:22:41', 'notis_saman', 'dokumen/summon/');
insert into \"saman\".\"summon_document\" ( \"ref_id\", \"is_primary\", \"created_by\", \"doc_name\", \"doc_path_thumbnail\", \"created_at\", \"doc_format\", \"updated_at\", \"doc_type\", \"doc_path\") values ( null, '0', '1', 'pMHDheY1C.pdf', null, '2021-08-11 18:24:02', 'pdf', '2021-08-11 18:24:02', 'notis_saman', 'dokumen/summon/');


insert into \"saman\".\"maklumat_kenderaan_saman\" ( \"alamat_pejabat_pemilik\", \"created_at\", \"pendaftaran_id\", \"summon_notice_doc_id\", \"user_id\", \"status_saman_id\", \"emel_ketua_jabatan\", \"updated_at\") values ( null, '2021-08-11 14:44:54', '3841', '1', null, '3', null, '2021-08-11 14:45:35');
insert into \"saman\".\"maklumat_kenderaan_saman\" ( \"alamat_pejabat_pemilik\", \"created_at\", \"pendaftaran_id\", \"summon_notice_doc_id\", \"user_id\", \"status_saman_id\", \"emel_ketua_jabatan\", \"updated_at\") values ( null, '2021-08-11 14:51:27', '3841', '2', null, '3', null, '2021-08-11 14:51:44');
insert into \"saman\".\"maklumat_kenderaan_saman\" ( \"alamat_pejabat_pemilik\", \"created_at\", \"pendaftaran_id\", \"summon_notice_doc_id\", \"user_id\", \"status_saman_id\", \"emel_ketua_jabatan\", \"updated_at\") values ( null, '2021-08-11 15:28:00', '3841', '3', null, '1', null, '2021-08-11 15:34:26');
insert into \"saman\".\"maklumat_kenderaan_saman\" ( \"alamat_pejabat_pemilik\", \"created_at\", \"pendaftaran_id\", \"summon_notice_doc_id\", \"user_id\", \"status_saman_id\", \"emel_ketua_jabatan\", \"updated_at\") values ( null, '2021-08-11 15:34:54', '3179', null, null, '3', null, '2021-08-11 15:36:52');
insert into \"saman\".\"maklumat_kenderaan_saman\" ( \"alamat_pejabat_pemilik\", \"created_at\", \"pendaftaran_id\", \"summon_notice_doc_id\", \"user_id\", \"status_saman_id\", \"emel_ketua_jabatan\", \"updated_at\") values ( null, '2021-08-11 17:05:42', '3179', '5', null, '4', null, '2021-08-11 17:11:50');
insert into \"saman\".\"maklumat_kenderaan_saman\" ( \"alamat_pejabat_pemilik\", \"created_at\", \"pendaftaran_id\", \"summon_notice_doc_id\", \"user_id\", \"status_saman_id\", \"emel_ketua_jabatan\", \"updated_at\") values ( null, '2021-08-11 18:15:47', '3148', '6', null, '3', null, '2021-08-11 18:15:53');
insert into \"saman\".\"maklumat_kenderaan_saman\" ( \"alamat_pejabat_pemilik\", \"created_at\", \"pendaftaran_id\", \"summon_notice_doc_id\", \"user_id\", \"status_saman_id\", \"emel_ketua_jabatan\", \"updated_at\") values ( null, '2021-08-11 18:17:16', '3838', '7', null, '3', null, '2021-08-11 18:17:22');
insert into \"saman\".\"maklumat_kenderaan_saman\" ( \"alamat_pejabat_pemilik\", \"created_at\", \"pendaftaran_id\", \"summon_notice_doc_id\", \"user_id\", \"status_saman_id\", \"emel_ketua_jabatan\", \"updated_at\") values ( null, '2021-08-11 18:19:09', '3701', '8', null, '4', null, '2021-08-11 18:19:13');
insert into \"saman\".\"maklumat_kenderaan_saman\" ( \"alamat_pejabat_pemilik\", \"created_at\", \"pendaftaran_id\", \"summon_notice_doc_id\", \"user_id\", \"status_saman_id\", \"emel_ketua_jabatan\", \"updated_at\") values ( null, '2021-08-11 18:21:10', '3729', '9', null, '4', null, '2021-08-11 18:21:15');
insert into \"saman\".\"maklumat_kenderaan_saman\" ( \"alamat_pejabat_pemilik\", \"created_at\", \"pendaftaran_id\", \"summon_notice_doc_id\", \"user_id\", \"status_saman_id\", \"emel_ketua_jabatan\", \"updated_at\") values ( null, '2021-08-11 18:22:41', '3816', '10', null, '4', null, '2021-08-11 18:22:46');
insert into \"saman\".\"maklumat_kenderaan_saman\" ( \"alamat_pejabat_pemilik\", \"created_at\", \"pendaftaran_id\", \"summon_notice_doc_id\", \"user_id\", \"status_saman_id\", \"emel_ketua_jabatan\", \"updated_at\") values ( null, '2021-08-11 18:24:02', '3824', '11', null, '4', null, '2021-08-11 18:24:06');


insert into \"saman\".\"maklumat_saman\" ( \"compound_reason\", \"state_id\", \"district_id\", \"notice_date\", \"maklumat_kenderaan_saman_id\", \"summon_notice_no\", \"updated_at\", \"mistake_date\", \"change_summon_owner_note\", \"created_by\", \"driver_id\", \"branch_id\", \"summon_agency_id\", \"jenis_saman\", \"owner_name\", \"total_compound\", \"summon_type_id\", \"mistake_time\", \"created_at\", \"change_summon_owner\", \"mistake_location\") values ( 'Melebihi had laju', '2', null, '2021-08-10', '1', '20012', '2021-08-11 14:44:54', '2021-08-10', null, '1', null, null, '1', null, null, '100', '1', '06:00:00', '2021-08-11 14:44:54', 'f', 'Jalan Setia');
insert into \"saman\".\"maklumat_saman\" ( \"compound_reason\", \"state_id\", \"district_id\", \"notice_date\", \"maklumat_kenderaan_saman_id\", \"summon_notice_no\", \"updated_at\", \"mistake_date\", \"change_summon_owner_note\", \"created_by\", \"driver_id\", \"branch_id\", \"summon_agency_id\", \"jenis_saman\", \"owner_name\", \"total_compound\", \"summon_type_id\", \"mistake_time\", \"created_at\", \"change_summon_owner\", \"mistake_location\") values ( 'laju', '1', null, '2021-08-01', '2', '20031', '2021-08-11 14:51:27', '2021-08-01', null, '1', null, null, '1', null, null, '300', '1', '12:00:00', '2021-08-11 14:51:27', 'f', 'asadasd');
insert into \"saman\".\"maklumat_saman\" ( \"compound_reason\", \"state_id\", \"district_id\", \"notice_date\", \"maklumat_kenderaan_saman_id\", \"summon_notice_no\", \"updated_at\", \"mistake_date\", \"change_summon_owner_note\", \"created_by\", \"driver_id\", \"branch_id\", \"summon_agency_id\", \"jenis_saman\", \"owner_name\", \"total_compound\", \"summon_type_id\", \"mistake_time\", \"created_at\", \"change_summon_owner\", \"mistake_location\") values ( 'Lebih had laju', '5', null, '2021-07-25', '3', '182736', '2021-08-11 15:28:00', '2021-07-25', null, '1', null, null, '2', null, null, '300', '1', '12:00:00', '2021-08-11 15:28:00', 'f', 'Rembau');
insert into \"saman\".\"maklumat_saman\" ( \"compound_reason\", \"state_id\", \"district_id\", \"notice_date\", \"maklumat_kenderaan_saman_id\", \"summon_notice_no\", \"updated_at\", \"mistake_date\", \"change_summon_owner_note\", \"created_by\", \"driver_id\", \"branch_id\", \"summon_agency_id\", \"jenis_saman\", \"owner_name\", \"total_compound\", \"summon_type_id\", \"mistake_time\", \"created_at\", \"change_summon_owner\", \"mistake_location\") values ( 'had laju', '9', null, '2021-08-01', '4', '20034', '2021-08-11 15:35:45', '2021-07-25', null, '1', null, null, '3', null, null, '300', '2', '12:00:00', '2021-08-11 15:35:45', 'f', 'gelugor');
insert into \"saman\".\"maklumat_saman\" ( \"compound_reason\", \"state_id\", \"district_id\", \"notice_date\", \"maklumat_kenderaan_saman_id\", \"summon_notice_no\", \"updated_at\", \"mistake_date\", \"change_summon_owner_note\", \"created_by\", \"driver_id\", \"branch_id\", \"summon_agency_id\", \"jenis_saman\", \"owner_name\", \"total_compound\", \"summon_type_id\", \"mistake_time\", \"created_at\", \"change_summon_owner\", \"mistake_location\") values ( 'trafik', '4', null, '2021-08-11', '5', '20059', '2021-08-11 17:05:42', '2021-08-01', null, '1', null, null, '1', null, null, '300', '1', '12:00:00', '2021-08-11 17:05:42', 'f', 'adsad');
insert into \"saman\".\"maklumat_saman\" ( \"compound_reason\", \"state_id\", \"district_id\", \"notice_date\", \"maklumat_kenderaan_saman_id\", \"summon_notice_no\", \"updated_at\", \"mistake_date\", \"change_summon_owner_note\", \"created_by\", \"driver_id\", \"branch_id\", \"summon_agency_id\", \"jenis_saman\", \"owner_name\", \"total_compound\", \"summon_type_id\", \"mistake_time\", \"created_at\", \"change_summon_owner\", \"mistake_location\") values ( 'lampu merah', '13', null, '2021-08-11', '6', '20084', '2021-08-11 18:15:47', '2021-07-29', null, '1', null, null, '2', null, null, '150', '1', '16:00:00', '2021-08-11 18:15:47', 'f', 'KL');
insert into \"saman\".\"maklumat_saman\" ( \"compound_reason\", \"state_id\", \"district_id\", \"notice_date\", \"maklumat_kenderaan_saman_id\", \"summon_notice_no\", \"updated_at\", \"mistake_date\", \"change_summon_owner_note\", \"created_by\", \"driver_id\", \"branch_id\", \"summon_agency_id\", \"jenis_saman\", \"owner_name\", \"total_compound\", \"summon_type_id\", \"mistake_time\", \"created_at\", \"change_summon_owner\", \"mistake_location\") values ( 'parkir lebih masa', '12', null, '2021-04-28', '7', '20044', '2021-08-11 18:17:16', '2021-04-26', null, '1', null, null, '3', null, null, '10', '2', '09:57:00', '2021-08-11 18:17:16', 'f', 'besut');
insert into \"saman\".\"maklumat_saman\" ( \"compound_reason\", \"state_id\", \"district_id\", \"notice_date\", \"maklumat_kenderaan_saman_id\", \"summon_notice_no\", \"updated_at\", \"mistake_date\", \"change_summon_owner_note\", \"created_by\", \"driver_id\", \"branch_id\", \"summon_agency_id\", \"jenis_saman\", \"owner_name\", \"total_compound\", \"summon_type_id\", \"mistake_time\", \"created_at\", \"change_summon_owner\", \"mistake_location\") values ( 'laju', '3', null, '2021-07-30', '8', '20054', '2021-08-11 18:19:09', '2021-07-06', null, '1', null, null, '2', null, null, '200', '1', '08:00:00', '2021-08-11 18:19:09', 'f', 'machang');
insert into \"saman\".\"maklumat_saman\" ( \"compound_reason\", \"state_id\", \"district_id\", \"notice_date\", \"maklumat_kenderaan_saman_id\", \"summon_notice_no\", \"updated_at\", \"mistake_date\", \"change_summon_owner_note\", \"created_by\", \"driver_id\", \"branch_id\", \"summon_agency_id\", \"jenis_saman\", \"owner_name\", \"total_compound\", \"summon_type_id\", \"mistake_time\", \"created_at\", \"change_summon_owner\", \"mistake_location\") values ( 'trafik', '5', null, '2021-05-01', '9', '20060', '2021-08-11 18:21:10', '2021-04-13', null, '1', null, null, '1', null, null, '500', '1', '00:00:00', '2021-08-11 18:21:10', 'f', 'seremban');
insert into \"saman\".\"maklumat_saman\" ( \"compound_reason\", \"state_id\", \"district_id\", \"notice_date\", \"maklumat_kenderaan_saman_id\", \"summon_notice_no\", \"updated_at\", \"mistake_date\", \"change_summon_owner_note\", \"created_by\", \"driver_id\", \"branch_id\", \"summon_agency_id\", \"jenis_saman\", \"owner_name\", \"total_compound\", \"summon_type_id\", \"mistake_time\", \"created_at\", \"change_summon_owner\", \"mistake_location\") values ( 'kemalangan', '12', null, '2021-06-24', '10', '20049', '2021-08-11 18:22:41', '2021-06-07', null, '1', null, null, '1', null, null, '600', '1', '16:00:00', '2021-08-11 18:22:41', 'f', 'kuala terengganu');
insert into \"saman\".\"maklumat_saman\" ( \"compound_reason\", \"state_id\", \"district_id\", \"notice_date\", \"maklumat_kenderaan_saman_id\", \"summon_notice_no\", \"updated_at\", \"mistake_date\", \"change_summon_owner_note\", \"created_by\", \"driver_id\", \"branch_id\", \"summon_agency_id\", \"jenis_saman\", \"owner_name\", \"total_compound\", \"summon_type_id\", \"mistake_time\", \"created_at\", \"change_summon_owner\", \"mistake_location\") values ( 'tali pinggang', '10', null, '2021-08-11', '11', '20044', '2021-08-11 18:24:02', '2021-07-27', null, '1', null, null, '3', null, null, '150', '2', '05:00:00', '2021-08-11 18:24:02', 'f', 'kota kinabalu');

      ");


    }
}
